name: build our image

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: install buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: build the image
        run: |
          docker buildx build --push \
            --tag ${{ secrets.DOCKER_USER }}/multi-arch-demo:${{ github.sha }} \
            --platform linux/amd64,linux/arm/v7,linux/arm64 .